
name: CI

on: 
  push:
    branches:
      - master
      - configure-ci

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.6'

    - name: Check Python Version
      run: |
        python -V

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        python test.py

    #- name: Lint Code
    #  run: |
    #    pylint app.py

    - name: Run Flask App
      run: |
        python app.py &
        sleep 10
        curl -sS http://127.0.0.1:8089 || exit 1