
name: CI

on: 
  push:
    branches:
      - master
      - configure-ci

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.X'

    - name: Install Dependencies
      run: |
        python -m pip install --upgradde pip
        pip install -r requirements.txt

    